FROM archlinux-rpi2
MAINTAINER nop-90

RUN pacman -Sy --noconfirm
RUN pacman -S mariadb --noconfirm

RUN sed -i -r 's/bind-address.*$/bind-address = 0.0.0.0/' /etc/mysql/my.cnf
VOLUME ["/var/lib/mysql"]

COPY assets/entrypoint.sh /sbin/
RUN chmod +x /sbin/entrypoint.sh

ENV TERM xterm
RUN chown -R mysql:mysql /var/lib/mysql
EXPOSE 3306
ENTRYPOINT ["/sbin/entrypoint.sh"]
